config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "foods#index"
  resources :foods, except: :update
   resources :recipes, except: :update do
   member do
   patch :toggle_public
   end
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
   end
  get '/general_shopping_list', to: 'shopping_list#index', as: 'general_shopping_list'

  get 'public_recipes', to: 'public_recipes#index', as: 'public_recipes'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, dependent: :destroy
  has_many :recipe, through: :recipe_foods
  validates :name, presence: true
  validates :price, presence: true
  validates :measurement_unit, presence: true
  validates :quantity, presence: true

  def self.total_price
    sum(:price)
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: true
  validates :cooking_time, presence: true, numericality: true
  validates :description, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def total_price
    recipe_foods.sum { |fd| fd.quantity * fd.food.price }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :food, :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods
  has_many :recipes
  has_many :recipe_foods, through: :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @user = current_user
    @food = @user.foods.build(foods_params)
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url, notice: 'Food item was successfully deleted.'
  end

  private

  def foods_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :find_recipe
  before_action :find_recipe_food, only: %i[edit update destroy]

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient successfully added.'
    else
      @foods = Food.all
      render :new
    end
  end

  def edit
    @foods = Food.all
  end

  def update
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe), notice: 'Ingredient updated successfully.'
    else
      @foods = Food.all
      render :edit
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to recipe_path(@recipe), notice: 'Ingredient deleted successfully.'
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def find_recipe_food
    @recipe_food = @recipe.recipe_foods.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user

  def index
    @recipes = @user.recipes.includes(:user) if user_signed_in?
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
  end

  def new
    @recipe = @user.recipes.build
  end

  def create
    @recipe = @user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = @user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe deleted successfully.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
    redirect_to recipe_path(@recipe), notice: "The recipe is now #{@recipe.public ? 'public' : 'private'}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe = current_user.recipes.find_by(id: params[:recipe_id])

    @recipe_foods = current_user.recipe_foods.group(:food_id).sum(:quantity)
    @foods = current_user.foods
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<div class="foods-container">
  <h1 class="header-food">Foods</h1>
  <button  class="add-food-btn">
    <%= link_to "Add food", new_food_path, class: "add-food" %>
  </button>
  <div class="foods">
    <% if @foods.empty? %>
      <p>No foods available.</p>
    <% else %>
      <table class="foods-table foodstuff">
        <thead class="table-head">
          <tr class="food-head">
            <th class="col">Food</th>
            <th>Measurement Unit</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr class="custom-table-row">
              <td class="food-names">
                <%= link_to food.name, food_url(current_user.id, food.id), class: "food-list" %>
              </td>
              <td><%= food.measurement_unit %></td>
              <td><%= food.quantity %></td>
              <td><span>$<%= food.price %></td></span>
              <td>
                <%= button_to "Delete",
                  food_path(food.id), method: :delete,
                  data: { confirm: "Delete food?" }, class: "delete-food" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<div class ="add-food-container">
<h1 class="new">Add New Food</h1>
<div class="food-container-new">
<%= form_with(model: @food, url: foods_path) do |form| %>
    <div class="form-food">
  <div class="labelf">
    <%= form.label :name %>
    <%= form.text_field :name, class: "name-1" %>
  </div>
  <div class="labelf">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit,class: "name-1" %>
  </div>
  <div class="labelf">
  <%= form.label :quantity %>
  <%= form.text_field :quantity, class: "name-1" %>
</div>
  <div class="labelf">
    <%= form.label :price %>
    <%= form.text_field :price, class: "name-2" %>
  </div>
  <div class="food-btn">
    <p><%= form.submit "Create Food", class: "new-food-btn" %></p>
  </div>
  </div>
<% end %>
<div>
</div>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <ul class="nav-list">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'Foods', foods_path %></li>
      <li class="nav-item"><%= link_to 'Recipes', recipes_path %></li>
      <li class="nav-item"><%= link_to 'Public Recipes', public_recipes_path %></li>
  </ul>
  <ul class="logout">
  <li class="nav-item-log-out"><%= button_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'manifest.js' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: 'layouts/navbar' %>
  <div class = "mainn-container">
    <%= yield %>
    </div>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1 class="h-center">Public Recipes</h1>
<div class="public-container">
  <% @public_recipes.each do |public_recipe| %>
    <div class="recipe-box">
      <div class="recipe-details">
        <div class="recipe-user">
          <%= link_to public_recipe.name, recipe_path(public_recipe), class: "name" %>
          <p>By: <%= public_recipe.user.name %></p>
        </div>
        <div class="price-count">
          <p>Total food items: <%= public_recipe.foods.count %></p>
          <p>Total price: <%= number_to_currency(public_recipe.foods.sum(:price)) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_foods/create.html.erb
<h1>RecipeFoods#create</h1>
<p>Find me in app/views/recipe_foods/create.html.erb</p>

app/views/recipe_foods/destroy.html.erb
<h1>RecipeFoods#destroy</h1>
<p>Find me in app/views/recipe_foods/destroy.html.erb</p>

app/views/recipe_foods/edit.html.erb
<h1 class="new">Edit Recipe Food</h1>

<div class="container">
  <% if flash[:error].present? %>
    <div class="alert">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch do |form| %>
    <div class="form-group">
      <%= form.label :food_id, "Food" %>
      <%= form.collection_select :food_id, @foods, :id, :name, { prompt: "Select new item" }, class: "input" %>
    </div>

    <div class="form-group">
      <%= form.label :quantity, "Quantity" %>
      <%= form.number_field :quantity, class: "input" %>
    </div>

    <div class="form-group">
      <%= form.submit "Update Recipe Food", class: "submit-btn-edit" %>
      <%= link_to "Cancel", recipe_path(@recipe), class: "submit-btn-edit" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/index.html.erb
<h1>RecipeFoods#index</h1>
<p>Find me in app/views/recipe_foods/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<h1 class="new">Add Ingredient to <%= @recipe.name %></h1>

<div class="container">
  <% if flash[:error].present? %>
    <div>
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with scope: :recipe_food, url: recipe_recipe_foods_path do |form| %>
    <div class="form-group">
      <%= form.label :food_id, "Food" %>
      <%= form.collection_select :food_id, @foods, :id, :name, { prompt: "Select food item" }, class: "input" %>
    </div>

    <div>
      <%= form.label :quantity, "Quantity" %>
      <%= form.number_field :quantity , class: "input" %>
    </div>

    <div class="form-group">
      <%= form.submit "Add Ingredient" , class: "submit-btn-edit"%>
      <%= link_to "Cancel", recipe_path(@recipe), class: "submit-btn-edit" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/show.html.erb
<h1>RecipeFoods#show</h1>
<p>Find me in app/views/recipe_foods/show.html.erb</p>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/index.html.erb
<div class="container">
  <%= link_to "Add recipe", new_recipe_path, class: "add-recipe" %>
</div>

<% @recipes.each do |recipe| %>
  <div class="recipe-container">
    <div class="name-btn-container">
      <%= link_to recipe.name, recipe_path(recipe), class: "recipe-name" %>
      <% if recipe.user == current_user %>
        <%= button_to 'REMOVE', recipe, method: :delete, class: 'remove-btn' %>
      <% end %>
    </div>
    <div class="desc-cont">
      <p class="description"> <%= recipe.description %></p>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<div class= "add-recipe-container">
<h1 class="new">Add New Recipe</h1>

<div class="recipe-container-new">
  <%= form_with model: @recipe, url: recipes_path, method: :post, local: true do |form| %>
    <div class="form-recipe">
    <div class="form">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "inputtt" %>
    </div>

    <div class="form">
      <%= form.label :preparation_time, "Preparation Time", class: "label" %>
      <%= form.number_field :preparation_time, class: "inputtt", step: 0.5 %>
    </div>

    <div class="form">
      <%= form.label :cooking_time, "Cooking Time", class: "label" %>
      <%= form.number_field :cooking_time, class: "inputtt", step: 0.5 %>
    </div>

    <div class="form">
      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "inputtt" %>
    </div>

    <div>
      <%= form.submit "Create Recipe", class: "recipe-btn" %>
    </div>
    </div>
  <% end %>
</div>
</div>

app/views/recipes/show.html.erb
<h1 class="new"><%= @recipe.name %></h1>

<div class="recipe-container-show">
  <div class="slider-details-cont">
    <div class="name-toggle">
      <p><strong>Preparation time :</strong> <%= @recipe.preparation_time %> hours</p>
      <p><strong>Cooking time :</strong> <%= @recipe.cooking_time %> hours</p>
       <p><strong>Steps go here...</strong></p>
    </div>

    <div class="toggle-container">
      <%= form_for @recipe, url: toggle_public_recipe_path(@recipe), method: :patch, remote: true, authenticity_token: true, html: { class: 'toggle-form' } do |f| %>
        <div class="slider-container">
          <span class="switch-label">
            <%= @recipe.public ? "Public" : "Private" %>
          </span>
          <label class="switch">  
            <%= f.check_box :public, { class: "toggle-switch" }, 0, 1 %>
            <span class="slider round"></span>
          </label>
        </div>
        <%= f.hidden_field :public, value: @recipe.public ? 0 : 1 %>
        <%= f.submit 'Toggle', class: 'hidden-submit', style: 'display: none;' %>
      <% end %>
    </div>
  </div>

  <div class="buttons">
    <%= link_to 'Generate Shopping List', general_shopping_list_path, class: "recipe-button-show" %>
    <% if @recipe.user == current_user %>
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe), class: "recipe-button-show" %>
    <% end %>
  </div>
  <hr>

  <div class="recipe-foods-container">
    <table class="recipe-foods-table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <tr>
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %></td>
            <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
            <td class="buttonss">
              <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'edit-btn-show' %>
              <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'remove-btn-show' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shopping_list/index.html.erb
<div class="shopping-container">
  <h1 class="h-center">Shopping List</h1>
  <div class="shopping-summary">
    <% @total_items = 0 %>
    <% @total_value = 0 %>
    <% @foods.each do |food| %>
      <% if @recipe_foods.key?(food.id) %>
        <% calculated_quantity = @recipe_foods[food.id].to_i - food.quantity.to_i %>
        <% if calculated_quantity > 0 %>
          <% @total_items += calculated_quantity %>
          <% @total_value += calculated_quantity * food.price %>
        <% end %>
      <% end %>
    <% end %>
    <div class="shopping">
      <div class="summary-item">
        <span>Amount of food items to buy:</span>
        <%= @total_items %>
      </div>
      <div class="summary-item">
        <span>Total value of food needed:</span>
        <span>$<%= @total_value %></span>
      </div>
    </div>
  </div>
  <table class="table-shopping">
    <thead class="table-head">
      <tr class="row-head">
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <% if @recipe_foods.key?(food.id) %>
          <% calculated_quantity = @recipe_foods[food.id].to_i - food.quantity.to_i %>
          <% if calculated_quantity > 0 %>
            <tr class="row-data">
              <td><%= food.name %></td>
              <td><%= calculated_quantity %></td>
              <td><span>$<%= calculated_quantity * food.price %></span></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>